server:
  port: 9005

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/purchase_record?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false



mybatis:
  mapper-locations: classpath:mapper/*.xml

